### PR TITLE
Spring clean.

### PR DESCRIPTION
**Pull request by vext01**
I need to make a change to phdrs for the tracer, but first some tidying.

See individual commits.

Assigning @ltratt due to licensing change.

### CODE REVIEW

**Comment by vext01** [comment]
(I've just realised I did the PR from the main repo, sorry, next one will be from a fork)

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
CI now enabled.

**Comment by ltratt** [comment]
I assume we want to turn off the Travis checks?

**Comment by vext01** [comment]
Yes, I'd like to kill travis.

They don't make this easy!

**Comment by vext01** [comment]
I've killed travis in 3 places. I'm hoping the status checks won't appear next PR...

**Pull request merged**
